# Generated by Django 3.1 on 2023-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='created_date',
        ),
        migrations.AddField(
            model_name='variation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
