# Generated by Django 3.1 on 2023-08-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230802_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='updated_date',
            new_name='created_date',
        ),
    ]
