# Generated by Django 3.1 on 2023-08-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230802_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='value',
            new_name='variation_value',
        ),
    ]
